# DVC Pipeline Configuration
# Defines the data processing and model training pipeline

stages:
  # Stage 1: Download and prepare data
  prepare_data:
    cmd: python scripts/prepare_data.py
    deps:
      - scripts/prepare_data.py
      - data/raw
      - params.yaml
    outs:
      - data/processed
    params:
      - prepare.image_size
      - prepare.train_ratio
      - prepare.val_ratio
      - prepare.test_ratio

  # Stage 2: Train model
  train:
    cmd: python src/models/train.py --data-dir data/processed --output-dir models
    deps:
      - src/models/train.py
      - src/models/cnn_model.py
      - src/data/preprocessing.py
      - src/data/dataset.py
      - data/processed
      - params.yaml
    outs:
      - models/model.pt
      - models/best_model.pt
      - models/training_curves.png
      - models/confusion_matrix.png
      - models/classification_report.txt
    plots:
      - models/training_curves.png:
          cache: false
      - models/confusion_matrix.png:
          cache: false

  # Stage 3: Evaluate model
  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - scripts/evaluate.py
      - models/model.pt
      - data/processed/test
    metrics:
      - models/evaluation_metrics.json:
          cache: false
    plots:
      - models/roc_curve.png:
          cache: false
