# DVC Parameters Configuration

# Data preparation parameters
prepare:
  image_size: 224
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  seed: 42

# Training parameters
train:
  model_type: cnn
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
  dropout_rate: 0.5
  seed: 42
